apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: db-ordenes
  name: db-ordenes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-ordenes
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: db-ordenes
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: ordenes_db
            - name: POSTGRES_PASSWORD
              value: ordenes_pass
            - name: POSTGRES_USER
              value: ordenes_user
          image: postgres:16-alpine
          name: db-ordenes
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
